<%@ taglib prefix="c" uri="/WEB-INF/view/module/legacyui/taglibs/c-rt.tld" %>
<%@ taglib prefix="openmrs" uri="/WEB-INF/view/module/legacyui/taglibs/openmrs.tld" %>
<%@ taglib prefix="openmrs_tag" tagdir="/WEB-INF/tags/module/legacyui" %>
<%@ taglib prefix="page" uri="/WEB-INF/view/module/legacyui/taglibs/page.tld" %>
<%@ taglib prefix="request" uri="/WEB-INF/view/module/legacyui/taglibs/request.tld" %>
<%@ taglib prefix="response" uri="/WEB-INF/view/module/legacyui/taglibs/response.tld" %>
<%@ taglib prefix="spring" uri="/WEB-INF/view/module/legacyui/taglibs/spring.tld" %>
<%@ taglib prefix="fn" uri="/WEB-INF/view/module/legacyui/taglibs/fn.tld" %>
<%@ taglib prefix="form" uri="/WEB-INF/view/module/legacyui/taglibs/spring-form.tld" %>